{% set name = "metrix_ml" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ccp4/{{ name }}/archive/main.tar.gz
  sha256: d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - numpy
    - scikit-learn
    - pandas
    - matplotlib-base

test:
  imports:
    - metrix_ml

about:
  home: https://github.com/ccp4/metrix_ml
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Machine learning tools for macromolecular crystallography'
  description: |
    Metrix ML provides machine learning tools and training pipelines for
    macromolecular crystallography data processing.
  dev_url: https://github.com/ccp4/metrix_ml

extra:
  recipe-maintainers:
    - multimeric
