package:
  name: imaris_convert_bioformats
  version: 1.0.0

source:
  - git_url: https://github.com/multimeric/ImarisConvertBioformats
    git_rev: 3fe6950d98f1431663feab0eb939988045d84790
    folder: .
  - git_url: https://github.com/imaris/ImarisWriter
    git_rev: b128e6e7d1a147261e9d5caf24ebc6b5c9c63779
    folder: ImarisWriter

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
  host:
    - boost
    - zlib
    - hdf5
    - lz4
    - openjdk<11
    - freeimage
  run:
    - boost
    - zlib
    - hdf5
    - lz4
    - openjdk<11
    - freeimage

about:
  home: https://github.com/shibukawa/imagesize_py
  license: MIT
  summary: 'Getting image size from png/jpeg/jpeg2000/gif file'
  description: |
    This module analyzes jpeg/jpeg2000/png/gif image header and
    return image size.
  dev_url: https://github.com/shibukawa/imagesize_py
  doc_url: https://pypi.python.org/pypi/imagesize
  doc_source_url: https://github.com/shibukawa/imagesize_py/blob/master/README.rst
