mkdir build
cd build
export PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig
export LDFLAGS="-L${PREFIX}/lib" 
export CFLAGS="-I${PREFIX}/include"
cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_PREFIX_PATH=${PREFIX} -DPKG_CONFIG_USE_CMAKE_PREFIX_PATH=True -DCMAKE_EXE_LINKER_FLAGS="-L$PREFIX/lib" -DCMAKE_MODULE_LINKER_FLAGS="-L$PREFIX/lib" -DCMAKE_SHARED_LINKER_FLAGS="-L$PREFIX/lib" -DCMAKE_STATIC_LINKER_FLAGS="-L$PREFIX/lib"
make
make install